services:
  qdrant:
    image: "qdrant/qdrant:v1.8.2"
    ports:
      - "6333:6333"
      - "6334:6334"

# curl http://localhost:6333/collections
# curl http://localhost:6333/collections/rag-workshop-collection
# curl -X PUT 'http://localhost:6333/collections/rag-workshop-collection' \
#      -H 'Content-Type: application/json' \
#      --data-raw '{
#        "vectors": {
#          "size": 384,
#          "distance": "Dot"
#        }
#      }'
