name: Update workshop packages
on:
  push:
    branches:
      - main

jobs:
  update_packages:
    name: Update
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Create packages
      run: ./scripts/create-packages.sh
    - name: Update release
      uses: ncipollo/release-action@v1.12.0
      with:
        name: Workshop packages
        tag: latest
        artifacts: "dist/*.tar.gz"
        allowUpdates: true
        removeArtifacts: true
